spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: r00t
  sql:
    init:
      mode: always

